### PR TITLE
Add pull request templates.

### PR DESCRIPTION
**Pull request by yu-kiat**
Just wanted to add this in here in order for pull requests to be tidy and maintainers can read the description without having to trawl through a few paragraph's worth of text.

(This should work.)

### CODE REVIEW

**Comment by yu-kiat** [comment]
The check failed because of rate limit???

**Comment by iinsertNameHere** [comment]
@yu-kiat This is a very good idea. Would be great to have one for Changes too. :)

**Comment by yu-kiat** [comment]
> @yu-kiat This is a very good idea. Would be great to have one for Changes too. :)

Alright, I'll add it soon.

**Comment by yu-kiat** [comment]
@iinsertNameHere I added it,

**Pull request merged**
